"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { Loader2, Plus, Save, ShieldCheck } from "lucide-react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { masterResumeSchema, type MasterResumeInput } from "@/lib/validations/resume";

export function MasterResumeForm() {
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<MasterResumeInput>({ resolver: zodResolver(masterResumeSchema), defaultValues: { title: "Currículo Mestre", summary: "Desenvolvedor frontend com experiência na construção de interfaces web acessíveis, responsivas e orientadas a produto.", phone: "+55 81 99999-9999", city: "Recife", state: "PE", portfolioUrl: "https://portfolio.example.com", linkedinUrl: "https://linkedin.com/in/exemplo", githubUrl: "https://github.com/exemplo", skills: "React, TypeScript, Next.js, Node.js, PostgreSQL, Tailwind CSS, Git, REST API, Testing Library", experienceRole: "Desenvolvedor Frontend", experienceCompany: "Studio Digital", experienceDescription: "Desenvolvimento de aplicações React e Next.js, colaboração com design e integração com APIs REST.", projectName: "Plataforma de oportunidades", projectDescription: "Aplicação web modular desenvolvida com Next.js, TypeScript e PostgreSQL.", educationInstitution: "Faculdade de Tecnologia", educationCourse: "Análise e Desenvolvimento de Sistemas" } });
  async function save() { await new Promise((resolve) => setTimeout(resolve, 700)); toast.success("Currículo mestre salvo."); }
  const error = (name: keyof MasterResumeInput) => errors[name] ? <p className="mt-1 text-xs text-destructive">{errors[name]?.message}</p> : null;
  return <form onSubmit={handleSubmit(save)} className="space-y-5">
    <Section title="Informações pessoais" description="Dados exibidos nas versões geradas."><div className="grid gap-4 sm:grid-cols-2"><Field label="Título do currículo" id="title" error={error("title")}><Input id="title" {...register("title")} /></Field><Field label="Telefone" id="phone"><Input id="phone" {...register("phone")} /></Field><Field label="Cidade" id="city"><Input id="city" {...register("city")} /></Field><Field label="UF" id="state"><Input id="state" maxLength={2} {...register("state")} /></Field><Field label="Portfólio" id="portfolioUrl" error={error("portfolioUrl")}><Input id="portfolioUrl" {...register("portfolioUrl")} /></Field><Field label="LinkedIn" id="linkedinUrl" error={error("linkedinUrl")}><Input id="linkedinUrl" {...register("linkedinUrl")} /></Field><Field label="GitHub" id="githubUrl" error={error("githubUrl")}><Input id="githubUrl" {...register("githubUrl")} /></Field></div></Section>
    <Section title="Resumo profissional" description="O gerador pode melhorar a redação, mas nunca criar fatos."><Label htmlFor="summary">Resumo *</Label><Textarea id="summary" className="min-h-32" {...register("summary")} />{error("summary")}</Section>
    <Section title="Tecnologias e competências" description="Separe cada item por vírgula."><Label htmlFor="skills">Competências *</Label><Textarea id="skills" className="min-h-24" {...register("skills")} />{error("skills")}</Section>
    <Section title="Experiência" description="A primeira experiência do seu histórico profissional."><div className="grid gap-4 sm:grid-cols-2"><Field label="Cargo *" id="experienceRole" error={error("experienceRole")}><Input id="experienceRole" {...register("experienceRole")} /></Field><Field label="Empresa *" id="experienceCompany" error={error("experienceCompany")}><Input id="experienceCompany" {...register("experienceCompany")} /></Field><div className="sm:col-span-2"><Label htmlFor="experienceDescription">Descrição *</Label><Textarea id="experienceDescription" {...register("experienceDescription")} />{error("experienceDescription")}</div></div><Button type="button" size="sm" variant="ghost" className="mt-3"><Plus className="size-3.5" />Adicionar experiência</Button></Section>
    <Section title="Projeto em destaque" description="Projetos comprovam competências sem inventar experiência."><div className="grid gap-4"><Field label="Nome" id="projectName"><Input id="projectName" {...register("projectName")} /></Field><div><Label htmlFor="projectDescription">Descrição</Label><Textarea id="projectDescription" {...register("projectDescription")} /></div></div></Section>
    <Section title="Formação" description="Informe apenas formações concluídas ou em andamento."><div className="grid gap-4 sm:grid-cols-2"><Field label="Instituição" id="educationInstitution"><Input id="educationInstitution" {...register("educationInstitution")} /></Field><Field label="Curso" id="educationCourse"><Input id="educationCourse" {...register("educationCourse")} /></Field></div></Section>
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><p className="inline-flex items-center gap-2 text-[11px] text-subtle"><ShieldCheck className="size-3.5" />Este documento é a única fonte de fatos para currículos gerados.</p><Button type="submit" disabled={isSubmitting}>{isSubmitting ? <Loader2 className="size-4 animate-spin" /> : <Save className="size-4" />}Salvar currículo mestre</Button></div>
  </form>;
}

function Section({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <section className="rounded-xl border border-border bg-surface p-5 sm:p-6"><div className="mb-5"><h2 className="text-sm font-semibold">{title}</h2><p className="mt-1 text-xs text-muted-foreground">{description}</p></div>{children}</section>; }
function Field({ label, id, error, children }: { label: string; id: string; error?: React.ReactNode; children: React.ReactNode }) { return <div><Label htmlFor={id}>{label}</Label>{children}{error}</div>; }
