import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowUpRight, Check, ChevronLeft, CircleAlert, MapPin, Minus, Sparkles, X } from "lucide-react";
import { auth } from "@/auth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { GenerateResumeButton } from "@/features/resume/generate-resume-button";
import { formatDate } from "@/lib/utils";
import { JobRepository } from "@/repositories/job.repository";
import { ResumeRepository } from "@/repositories/resume.repository";
import { JobMatchService } from "@/services/job-match.service";

export default async function JobDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const session = await auth();
  if (!session?.user.id) notFound();
  const [job, resume] = await Promise.all([new JobRepository().findById(session.user.id, id), new ResumeRepository().findMaster(session.user.id)]);
  if (!job) notFound();
  const requirements = job.requirements.map((item) => item.name);
  const match = resume ? new JobMatchService().calculate(requirements, [...resume.skills.map((item) => ({ value: item.name, evidence: `Competência: ${item.name}` })), ...resume.projects.flatMap((project) => project.technologies.map((value) => ({ value, evidence: `Projeto: ${project.name}` })))]) : { score: 0, items: [] };
  const grouped = { matched: match.items.filter((item) => item.level === "MATCHED").map((item) => item.requirement), partial: match.items.filter((item) => item.level === "PARTIAL").map((item) => item.requirement), missing: match.items.filter((item) => item.level === "MISSING").map((item) => item.requirement) };

  return <div className="space-y-6"><Link href="/vagas" className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground"><ChevronLeft className="size-3.5" />Voltar para vagas</Link>
    <header className="flex flex-col justify-between gap-5 border-b border-border pb-6 lg:flex-row lg:items-end"><div><div className="mb-3 flex flex-wrap gap-2"><Badge>{match.score}% de compatibilidade</Badge><Badge variant="neutral">{job.status === "ANALYZED" ? "Analisada" : "Salva"}</Badge></div><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">{job.title}</h1><div className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-muted-foreground"><span>{job.company ?? "Empresa não informada"}</span><span className="inline-flex items-center gap-1"><MapPin className="size-3.5" />{job.location ?? "Local não informado"} · {job.workMode ?? "Modalidade não informada"}</span><span>{formatDate(job.createdAt)}</span></div></div><div className="flex flex-wrap gap-2"><GenerateResumeButton jobId={job.id} />{job.url ? <Button asChild variant="secondary" size="icon"><a href={job.url} target="_blank" rel="noreferrer" aria-label="Abrir vaga"><ArrowUpRight className="size-4" /></a></Button> : null}</div></header>
    <div className="grid gap-5 xl:grid-cols-[1.3fr_0.7fr]"><div className="space-y-5"><Card><CardHeader><div><h2 className="text-sm font-semibold">Compatibilidade ATS</h2><p className="mt-1 text-xs text-muted-foreground">Comparação objetiva com o Currículo Mestre</p></div><span className="font-mono text-3xl font-semibold text-accent">{match.score}%</span></CardHeader><CardContent><Progress value={match.score} className="h-2" /><div className="mt-6 grid gap-5 sm:grid-cols-3"><RequirementGroup icon={Check} label="Compatível" tone="success" items={grouped.matched} /><RequirementGroup icon={Minus} label="Parcial" tone="warning" items={grouped.partial} /><RequirementGroup icon={X} label="Não encontrado" tone="danger" items={grouped.missing} /></div><div className="mt-6 flex gap-3 rounded-lg border border-border bg-background p-3"><CircleAlert className="mt-0.5 size-4 shrink-0 text-muted-foreground" /><p className="text-xs leading-5 text-muted-foreground">Competências ausentes permanecem fora do currículo gerado. A IA só pode ordenar os fatos verificados.</p></div></CardContent></Card>
      <Card><CardHeader><div><h2 className="text-sm font-semibold">Descrição original da vaga</h2><p className="mt-1 text-xs text-muted-foreground">Texto usado na análise e na personalização</p></div><Sparkles className="size-4 text-accent" /></CardHeader><CardContent><p className="whitespace-pre-line text-sm leading-7 text-muted-foreground">{job.description}</p></CardContent></Card></div>
      <div className="space-y-5"><Card><CardHeader><h2 className="text-sm font-semibold">Próxima ação</h2></CardHeader><CardContent><p className="text-xs leading-5 text-muted-foreground">Gere uma versão em coluna única, com títulos convencionais, texto selecionável e palavras-chave comprovadas para leitura por ATS.</p><GenerateResumeButton jobId={job.id} className="mt-4 w-full" /></CardContent></Card><Card><CardHeader><h2 className="text-sm font-semibold">Palavras-chave extraídas</h2></CardHeader><CardContent className="flex flex-wrap gap-2">{requirements.length ? requirements.map((item) => <Badge key={item} variant="neutral">{item}</Badge>) : <p className="text-xs text-subtle">Nenhum requisito explícito foi extraído.</p>}</CardContent></Card><Card><CardHeader><h2 className="text-sm font-semibold">Dados da vaga</h2></CardHeader><CardContent className="space-y-3 text-xs"><DataRow label="Origem" value={job.source ?? "Manual"} /><DataRow label="Modalidade" value={job.workMode ?? "Não informada"} /><DataRow label="Localização" value={job.location ?? "Não informada"} /><DataRow label="Salário" value={job.salary ?? "Não informado"} /></CardContent></Card></div></div>
  </div>;
}
function RequirementGroup({ icon: Icon, label, items, tone }: { icon: typeof Check; label: string; items: string[]; tone: "success" | "warning" | "danger" }) { const tones = { success: "text-emerald-400 bg-emerald-500/10", warning: "text-amber-400 bg-amber-500/10", danger: "text-red-400 bg-red-500/10" }; return <div><h3 className="mb-3 text-[10px] font-semibold uppercase tracking-wider text-subtle">{label}</h3><div className="space-y-2">{items.length ? items.map((item) => <div key={item} className="flex items-center gap-2 text-xs"><span className={`grid size-5 place-items-center rounded ${tones[tone]}`}><Icon className="size-3" /></span><span>{item}</span></div>) : <p className="text-xs text-subtle">Nenhum</p>}</div></div>; }
function DataRow({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4"><span className="text-muted-foreground">{label}</span><span className="text-right text-foreground">{value}</span></div>; }
